### ISSUE TITLE
Widget does not react on keyboard input

### ISSUE THREAD

**Issue by RobinTimmerman92** [Itvisors/mendix-ReactDateTimePicker#2]
It seems you can only choose a date and time by clicking a date and a time right from the widget.
When you afterwards adjust the time by changing it with your keyboard in the input field, the datetime attribute is actually not changed, whereas for an end-user it seems changed. This leads to unexpected behavior for users.

**Comment by jeuhen** [comment]
Hi Robin,
This issue should not occur in the widget I published in the app store. Do you also have this bug with that widget, or did you try to change the widget itself? If you also have this bug with the widget published in the app store, could you share some details how I can reproduce?

**Comment by RobinTimmerman92** [comment]
Hi Johan,

I’ve used the latest version of the widget in the Mendix Appstore.
I think I’ve found out when the ‘bug’ occurs.
In case you use a custom ‘Date format’ like ‘dddd DD/MM/YYYY’ (or ‘dd’/’ddd’ instead of ‘dddd’) the widget does not react on keyboard input.
When I remove the ‘dddd’ part, the widget works properly.
For our usecase the ‘dddd’ part is highly desirable by end users.
Is this something that can be fixed easily?

KR,
Robin

**Comment by jeuhen** [comment]
Hi Robin, good one. This seems to go wrong when using a locale setting, combined with the dddd in the format. Unfortunately this is a bug in the currently used library. When I upgrade the widget, I will keep this in mind and see what I can do.
 Is it an option for you to leave the dddd in the widget itself? Perhaps you can display it next to it? I can imagine this is not preferred, but when using dddd, you also have to change the day 'Monday' to another day when changing the date.

**Comment by jeuhen** [comment]
Hi Robin,
I just updated the widget and this should work now. Can you try again?
Kind regards,
Johan
