### ISSUE TITLE
invalid date behavier

### ISSUE THREAD

**Issue by bs-baba** [Itvisors/mendix-ReactDateTimePicker#5]
If a user puts an invalid date (e.g., string or 4/31/2022) into a widget text box directly, no alert is displayed in the UI and the user is unaware that it is invalid.

Not only that, when saving in Microflow, the attribute with the invalid date will be empty.
Therefore, it is impossible to determine if an invalid date was entered or if the user wanted to save it as empty, so Validation Feedback cannot be performed properly.
Is there any good solution to this problem?

**Comment by bs-baba** [comment]
Ideally, as with the Mendix standard DatePicker, as long as an invalid date is entered, the Feedback message will continue to be displayed and Microflow cannot be called.

**Comment by jeuhen** [comment]
Did you try the Valid date property? This attribute will be set to false when an invalid date is entered, a feedback message can be set in the onchange flow. Hope this helps!

**Comment by bs-baba** [comment]
Hi jeuhen, thanks for the comment. I understand now how to use the Valid date property!
