### ISSUE TITLE
show calendar in forefront

### ISSUE THREAD

**Issue by bs-baba** [Itvisors/mendix-ReactDateTimePicker#6]
When I display the React DateTime Picker in a small height popup or in DataGrid2, the bottom part of the calendar is hidden.
The z-index value seems high enough.
I cannot make the popup or DataGrid2 larger just to get around this.
Is it possible to always display it in the forefront like the standard DatePicker in Mendix?
![Calendar](https://user-images.githubusercontent.com/38234320/164447153-03cc4a26-f09c-4c36-a385-40f366245d20.png)

**Comment by jeuhen** [comment]
You can try to add position:fixed to .rdt .rdtPicker.
Does this solve your problem?

**Comment by bs-baba** [comment]
Hi jeuhen,
Thanks for your comment.
That solved the problem with popups, but not with DataGrid2.
If using position:fixed, is it neccesary to set the left and top values dynamically?

**Comment by jeuhen** [comment]
I just tried in Datagrid2 and see that the calendar scrolls along, so this can indeed cause weir behavior.

I tried some different things, but it seems to work if you set .rdt { position: static } (and not the position fixed on the rdtPicker),  can you give this a try?

**Comment by bs-baba** [comment]
Hi jeuhen,
Thanks for your comment.
I tried that and nothing changed the result.
Did you just add .rdt { position: static } only and it worked fine?

**Comment by bs-baba** [comment]
Hi jeuhen,
If possible, can you give us a sample mpr or sass file that you have used successfully with DataGrid2?
I would like to use that as a reference to investigate why I am not getting it right.

**Comment by bs-baba** [comment]
I think position: fixed to .rdt .rdtPicker is effective for displaying in the foreground.
However, as mentioned above, I think it is necessary to dynamically set the values of top and left.
This is because if the page is long and the widget is located at the bottom, the default calendar position is set outside the scroll range and is invisible.
It would be nice to be able to dynamically set the top and left values when rendering with JavaScript. Is that possible?

**Comment by bs-baba** [comment]
I have applied position: fixed and then attempted to change the render function in ReactDateTimePicker.js so that the position is set in JavaScript when the calendar is rendered.

I have confirmed that it is possible to set the position as long as it is static. However, I need to set the position dynamically, excluding the scroll offset, but I don't know how to get that value. Is my approach correct? Any ideas?

The following code is a modification of ReactDateTimePicker.js in mpk around line 25055.

```
		// for test
		var rdtStyle = {
			top: '200px',  // should be set position of excluded the scrollY offset
			left: '200px'  // should be set position of excluded the scrollX offset
		};

		return React.createElement( ClickableWrapper, {className: className, onClickOut: this.handleClickOutside}, children.concat(
			React.createElement( 'div',
				{ key: 'dt', className: 'rdtPicker', style: rdtStyle },
				React.createElement( CalendarContainer, { view: this.state.currentView, viewProps: this.getComponentProps() })
			)
		));
```

**Comment by jeuhen** [comment]
Hi bs-baba,

Sorry for the late response.
This indeed sounds like a good solution. 
I will add this to my list to pick-up for a new release, but do not yet know when I can pick this up.

However I now only get issues for the popup. If I add no styling and use the latest version of data grid 2.0 and the widget, it works for me. Can you share what is the error you get (when you have no additional styling, also not the position fixed)?
![image](https://user-images.githubusercontent.com/10990959/171817691-11ffd2b5-1b35-4283-acb4-a7d82ea57c6c.png)

If this is working, perhaps you can only use position fixed in the popup as workaround for now

**Comment by bs-baba** [comment]
Hi jeuhen,

Thank you for your reply.
I apologize for not explaining my situation correctly.

When I used only DataGrid2 and ReactDateTimePicker without adding any styles, the calendar was displayed without any problem, as you said.

However, in our application we need to put the DataGrid2 inside the ScrollContainer.
In that case, the bottom part of the calendar was hidden. We want it to always be in the foreground.
![image](https://user-images.githubusercontent.com/38234320/172582366-55482d10-2740-4be7-bbdc-adea1301e532.png)

Adding the style 'position:fixed' seemed like a good way to do it.
However, if the screen is long vertically and DataGrid2 is at the bottom, the calendar will be positioned off-screen and not visible.
Our current problem is that we want to set this display position dynamically.
![image](https://user-images.githubusercontent.com/38234320/172583448-38dfd7c2-d955-4225-8d36-081b604fce37.png)

**Comment by bs-baba** [comment]
We have solved this problem.
Instead of modifying the JavaScript in the React DateTime Picker, we now execute separate JavaScript code when the screen loads.
In that code, we added an event listener to the React DateTime Picker button to dynamically set the TOP and LEFT of the calendar.
Thank you.

**Comment by jeuhen** [comment]
Great that you solved it. I still want to update this logic in the widget in a next release. So you can check after some time whether you can update it and delete the custom js :)
