### ISSUE TITLE
Clear invalid value in text box

### ISSUE THREAD

**Issue by bs-baba** [Itvisors/mendix-ReactDateTimePicker#7]
We would like to automatically clear the input value if an invalid date is entered directly into a widget text box.

We understand that the Valid date property can be used to check the input in Microflow. ([I was taught this in this Issue.](https://github.com/Itvisors/mendix-ReactDateTimePicker/issues/5) Thank you!)
However, in our application, there are many places where dates are entered using this widget, and it would be a huge burden on the developer to set the Valid date property on all of them.

So we are looking into the possibility of customizing the JavaScript of the widget to automatically empty the text box if an invalid value is entered.
It looks like we should implement that process around line 27000, but is it possible to clear the text box here? What would be the implementation?
![image](https://user-images.githubusercontent.com/38234320/172587600-5520d08f-1578-4f55-8399-f6621ab1ef01.png)

**Comment by bs-hayashi** [comment]
I would appreciate it if you would update me on this matter.

**Comment by bs-hayashi** [comment]
Would you kindly give your reply, as your response is very important to us.

**Comment by jeuhen** [comment]
Hi both,

I can understand that this is indeed not wanted and can be improved. One way is to do it in ReactDateTimePicker.tsx on the place you show and set the value of the dateTimeAttribute to undefined. However you need to rerender the component to make sure the value is cleared. 

You can always make a fork and submit a PR. I will add it to my list, but not sure yet when I can pick it up.

**Comment by bs-baba** [comment]
Hi jeuhen,

Thanks for reply.
Could you please give me some more advice?
How can I rerender the component in the onBlur method?

I put the following statement inside an else (Line 27003): 
`this.props.dateTimeAttribute.setValue(undefined);`
But the textbox was not cleared.

**Comment by bs-baba** [comment]
Hi jeuhen,

Sorry if this is an elementary question.
Is to rerender the component a common implementation in Custom Widgets?
I just want to know if your idea is feasible.

Thank you.

**Comment by jeuhen** [comment]
Hi,
You have to make sure that the render method is triggered. This can for example be done by updating something in the state.
You can find a lot on this on google or the react documentation.
Hope this helps!

**Comment by bs-baba** [comment]
Hi,
We were finally able to fix it to clear the values on rerender.
Thanks for the advice!
