### ISSUE TITLE
Silent time validation violations

### ISSUE THREAD

**Issue by Liamhanninen** [Itvisors/mendix-ReactDateTimePicker#9]
Thanks for your time and this tool. It's been very helpful.

Time validation violations seem to occur silently (I'm not sure if applies to dates). If the user enters 25:15 I would expect some validation error to display. But nothing happens. In the on change microflow I can see the value is empty but the user's value is still populated in the field - and they may not notice.  They could save and leave the record and it will be empty when they return. If I want to handle this myself (using the on change microflow in concert with the 'Valid date' boolean) I can't assume that the value _should_ be empty because the user could be removing the value. 
To illustrate this further it seems like the only way to handle this right now is check if it's empty (which would mean it was either deleted by the user or the user entered an invalid time) and then provide a pop-up saying as such: "The value you entered is invalid or you just deleted the value".
Note I have tried adjusting the min/max hour/minutes and that doesn't seem to impact this. 

To conclude: Is there a way I can know that the time picker identified an invalid time so I can trigger a validation message to the user? Otherwise this seems like a bit of an oversight/bug.

**Comment by jeuhen** [comment]
Hi Liam,

Thanks for your feedback. You can use the "Valid Date" property to see whether a valid date is entered or not. You can use this boolean in e.g. the onchange microflow to show a validation message. If the user clears the value, the "Valid Date" property will be set to true. So if valid date is false, there should always be an invalid value in the datepicker. 
So if you first check on valid date and later on empty, you can distinct know if the value is really empty or just invalid.

It is still on my list to improve this logic, but this was previously not possible.

Hope this helps!

**Comment by jeuhen** [comment]
Since I did not get a response, I assume above fixed you issue. If not, please re-open.
